services:
  circle-db:
    image: postgres:16
    container_name: circle-db
    ports:
      - "5432:5432"
    env_file:
      - ./server/.env
    networks:
      - circle-network
    volumes:
      - circle-data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  circle-data:

networks:
  circle-network:
    driver: bridge
    name: circle-net